export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      {/* <p>This is layout</p> */}
      <body>{children}</body>
    </html>
  )
}
